name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Heya
        run: echo 'Jonas likes you <3'
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and Push
        run: | 
          docker build -t chat .
          docker push chat
